# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:
services:

  zookeeper1.ideal.com:
    container_name: zookeeper1.ideal.com
    extends:
      file: zookeeper-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
    ports:
      - 2181:2181
      - 2188:2888
      - 3888:3888
    networks:
      - byfn 

  zookeeper2.ideal.com:
    container_name: zookeeper2.ideal.com
    extends:
      file: zookeeper-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
    ports:
      - 4181:2181
      - 4288:2888
      - 4388:3888
    networks:
      - byfn 

  zookeeper3.ideal.com:
    container_name: zookeeper3.ideal.com
    extends:
      file: zookeeper-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
    ports:
      - 5181:2181
      - 5288:2888
      - 5388:3888
    networks:
      - byfn 



  
      
